# Generated by Django 4.1.7 on 2023-03-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('products', '0004_alter_tag_name_specification_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='category',
        ),
        migrations.AddField(
            model_name='specification',
            name='category',
            field=models.ManyToManyField(related_name='specifications', to='catalog.category', verbose_name='категория'),
        ),
    ]
