# Generated by Django 4.1.7 on 2023-03-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_reviews_reviews_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='href',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='title',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='specification_name', to='products.specification', verbose_name='название'),
            preserve_default=False,
        ),
    ]
